ExchangeOffice/Controllers/BlagajnaController.cs
using System.Globalization;
using System.Linq;
using System.Web.Mvc;
using ExchangeOffice.Business;
using ExchangeOffice.DataAccessLayer;
using ExchangeOffice.ViewModels;

namespace ExchangeOffice.Controllers
{
    [Authorize]
    public class BlagajnaController : Controller
    {
        // GET: Blagajna
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Uplata()
        {
            ModelState.Clear();
            return PartialView("_UplataPartial", new UplataViewModel());
        }

        [HttpPost]
        public ActionResult Uplata(UplataViewModel wm)
        {
            if (ModelState.IsValid == false)
            {
                Response.StatusCode = 400;
                return PartialView("_UplataPartial", wm);
            }

            ExchangeEngine.Izvrsi(new UplataCmd()
            {
                Iznos = wm.Iznos.Value,
                SifraValuta = wm.SifraValuta
            });

            return new HttpStatusCodeResult(200);
        }
        
        public JsonResult VratiRacune()
        {
            var racuni = ExchangeRepository.VratiSveRacuneBlagajne();

            var result = racuni.Select(it => new
            {
                it.SifraValute,
                Stanje = it.Stanje.ToString(CultureInfo.InvariantCulture),
                it.Opis
            }).ToList();

            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

ExchangeOffice/Controllers/KursnaListaController.cs
using System;
using System.Globalization;
using System.Linq;
using System.Web.Mvc;
using ExchangeOffice.DataAccessLayer;
using ExchangeOffice.ViewModels;

namespace ExchangeOffice.Controllers
{
    [Authorize]
    public class KursnaListaController : Controller
    {
        // GET: KursnaLista
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult VratiKursneListe()
        {

            var kursneListe = ExchangeRepository.VratiSveKursneListe();

            var result = kursneListe
                .OrderByDescending(it => it.Datum)
                .Select(it => new
                KursnaListaIndexViewModel
                {
                    SifraValute = it.SifraValute,
                    Datum = it.Datum.ToShortDateString(),
                    Opis = it.Opis
                }).ToList();

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public JsonResult VratiStavkeListe(string izabraniDatum,string izabranaValuta)
        {
            var stavkeKursneListe = ExchangeRepository.VratiStavkeKursneListe(izabraniDatum, izabranaValuta);

            var result = stavkeKursneListe.Select(it => new StavkeKursneListeIndexViewModel
            {
                Valuta = it.SifraValutaStavke,
                KupovniKurs = it.KupovniKurs.ToString(CultureInfo.CurrentCulture),
                ProdajniKurs = it.ProdajniKurs.ToString(CultureInfo.CurrentCulture),
                SrednjiKurs = it.SrednjiKurs.ToString(CultureInfo.CurrentCulture),
            }).ToList();

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult KreirajDanasnjuListu()
        {
            try
            {
                ExchangeRepository.KreirajDanasnjuKursnuListu();

                return new HttpStatusCodeResult(200);
            }
            catch (Exception)
            {
                return new HttpStatusCodeResult(400);
            }
        }

        [HttpPost]
        public ActionResult IzmeniStavkuKursneListe(StavkaKursneListeEditViewModel wm)
        {
            if (ModelState.IsValid == false)
            {
                Response.StatusCode = 400;
                return PartialView("_IzmeniStavkuPartial", wm);
            }

            try
            {
                ExchangeRepository.IzmeniStavkuKursneListe(wm.ValutaListe, wm.DatumListe, wm.Valuta, wm.KupovniKurs, wm.SrednjiKurs, wm.ProdajniKurs);

                return new HttpStatusCodeResult(200);
            }
            catch (Exception)
            {
                Response.StatusCode = 400;
                return PartialView("_IzmeniStavkuPartial", wm);
            }
        }
    }
}

ExchangeOffice/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Menjčnica</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body id="page-top">
    <nav class="navbar navbar-expand navbar-dark bg-dark static-top">
        <a class="navbar-brand mr-1" href="index.html">Menjačnica</a>
        <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
            <i class="fas fa-bars"></i>
        </button>
        <!-- Navbar Search -->
        <form class="d-md-inline-block  ml-auto "></form>
        <!-- Navbar -->
        @Html.Partial("_LoginPartial")
    </nav>
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="sidebar navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","Home")">
                    <i class="fas fa-fw fa-money-bill-alt"></i>
                    <span>Transakcije</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","Blagajna")">
                    <i class="fas fa-fw fa-university"></i>
                    <span>Blagajna</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href=@Url.Action("Index","KursnaLista")>
                    <i class="fas fa-fw fa-chart-line"></i>
                    <span>Kursne liste</span>
                </a>
            </li>
        </ul>
        <div id="content-wrapper">
            <div class="container-fluid" style="height: 80vh ">


                @RenderBody()


            </div>
            <!-- /.container-fluid -->
            <!-- Sticky Footer -->
            @*<footer class="sticky-footer">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>© Menjačnica 2018</span>
                    </div>
                </div>
            </footer>*@
        </div>
        <!-- /.content-wrapper -->
    </div>
    <!-- /#wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>


    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>


    @Scripts.Render("~/bundles/js")
    @Scripts.Render("~/bundles/jqueryval")
    @RenderSection("scripts", required: false)
</body>
</html>